spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsSystem?serverTimezone=Asia/Shanghai&useunicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create